### ISSUE TITLE
Working on avoiding CraftManager!  No output, does not export.

### ISSUE THREAD

**Issue by renemarcelo** [vconesa/justinmind-sketch#8]
On Sketch 66.1

It is not launching anything to the best of my knowledge.  I downloaded a dev-tools and was able to get this output.

I am expecting to get an artboard export to Justinmind, but get no output.

Thank you so much,
-R

```
MOJavaScriptException: TypeError: context.api is not a function. (In 'context.api()', 'context.api' is null)
readContextParameters ExportToJustinmind.cocoascript:3102:26
onExportAllLayers ExportToJustinmind.cocoascript:3076:24
```

**Comment by renemarcelo** [comment]
Looks great and working on 66.1
![Screen Shot 2020-06-03 at 10 27 30 PM](https://user-images.githubusercontent.com/1162669/83711657-6d6c5280-a5e9-11ea-8059-fb46a80d720a.png)

I appreciate it!
-R
